title: Nicholas Geraedts' Blog
author:
  name: Nicholas Geraedts
  email: ngeraedts@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Thoughts on life and technology.

permalink: "/posts/:title/"

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mermaid
